### ISSUE TITLE
I'm sorry, I don't understand Output.

### ISSUE THREAD

**Issue by HackYardo** [SchroederLionel/KataGO_Data_Enhancer#1]
I'm sorry again, I can't speak Java, so I can't use this repo.
Although Output has 20 (5*4) kinds of data, the most interesting to me is the Euclidean distance (Ed).
What does Ed mean in your repo? 
- [ ] Stone A at (3,3), Stone B at (16,4), Ed = ((16-3)^2+(4-3)^2))^0.5
- [ ] Move A has value-vector (2.0,1,3,2,2) Move B has value-vector (5.5,2,7,6,4), Ed = ...

**Comment by HackYardo** [comment]
Seems too long to pick up

**Comment by SchroederLionel** [comment]
Hey I didnt pay attention on this email. Ed is the euclidien distance
between two stones. One move is x and y not multiple values. I try to
understand your question x) please explain more . I can also speak french
and  german
